export const GET_FULL_COLLECTION_DATA_REQUEST =
	'GET_FULL_COLLECTION_DATA_REQUEST'
export const GET_FULL_COLLECTION_DATA_SUCCESS =
	'GET_FULL_COLLECTION_DATA_SUCCESS'
export const GET_FULL_COLLECTION_DATA_FAILURE =
	'GET_FULL_COLLECTION_DATA_FAILURE'
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'
