export const GET_HITS_COLLECTIONS_REQUEST = 'GET_HITS_COLLECTIONS_REQUEST'
export const GET_HITS_COLLECTIONS_SUCCESS = 'GET_HITS_COLLECTIONS_SUCCESS'
export const GET_HITS_COLLECTIONS_FAILURE = 'GET_HITS_COLLECTIONS_FAILURE'
