export const GET_HITS_CATEGORIES_SUCCESS = 'GET_HITS_CATEGORIES_SUCCESS'
export const GET_HITS_CATEGORIES_REQUEST = 'GET_HITS_CATEGORIES_REQUEST'
export const GET_HITS_CATEGORIES_FAILURE = 'GET_HITS_CATEGORIES_FAILURE'
