export const GET_SALE_COLLECTIONS_REQUEST = 'GET_SALE_COLLECTIONS_REQUEST'
export const GET_SALE_COLLECTIONS_SUCCESS = 'GET_SALE_COLLECTIONS_SUCCESS'
export const GET_SALE_COLLECTIONS_FAILURE = 'GET_SALE_COLLECTIONS_FAILURE'
