export const GET_SALE_CATEGORIES_SUCCESS = 'GET_SALE_CATEGORIES_SUCCESS'
export const GET_SALE_CATEGORIES_REQUEST = 'GET_SALE_CATEGORIES_REQUEST'
export const GET_SALE_CATEGORIES_FAILURE = 'GET_SALE_CATEGORIES_FAILURE'
