export const SEARCH_COLLECTIONS_REQUEST = 'SEARCH_COLLECTIONS_REQUEST'
export const SEARCH_COLLECTIONS_SUCCESS = 'SEARCH_COLLECTIONS_SUCCESS'
export const SEARCH_COLLECTIONS_FAILURE = 'SEARCH_COLLECTIONS_FAILURE'
