export const GET_SEARCH_CATEGORIES_REQUEST = 'GET_SEARCH_CATEGORIES_REQUEST'
export const GET_SEARCH_CATEGORIES_SUCCESS = 'GET_SEARCH_CATEGORIES_SUCCESS'
export const GET_SEARCH_CATEGORIES_FAILURE = 'GET_SEARCH_CATEGORIES_FAILURE'
