export const GET_PARENTS_CATEGORIES_REQUEST = 'GET_PARENTS_CATEGORIES_REQUEST'
export const GET_PARENTS_CATEGORIES_SUCCESS = 'GET_PARENTS_CATEGORIES_SUCCESS'
export const GET_PARENTS_CATEGORIES_FAILURE = 'GET_PARENTS_CATEGORIES_FAILURE'

export const CREATE_CATALOG_TREE = 'CREATE_CATALOG_TREE'
