export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE'

export const GET_ALL_CHILDREN_REQUEST = 'GET_ALL_CHILDREN_REQUEST'
export const GET_ALL_CHILDREN_SUCCESS = 'GET_ALL_CHILDREN_SUCCESS'
export const GET_ALL_CHILDREN_FAILURE = 'GET_ALL_CHILDREN_FAILURE'
