export { MainSlider } from './MainSlider'
export { ProductSlider } from './ProductSlider'
export { default as VkPosts } from './VkPosts'
export { default as HomeNews } from './HomeNews'
export { default as HitsSlider } from './HitsSlider'
export { default as SaleSlider } from './SaleSlider'
