export { default as MainSlider } from './MainSlider'
export { default as VkPosts } from './VkPosts'
export { default as HomeNews } from './HomeNews'
export { default as HitsSlider } from './HitsSlider'
export { default as SaleSlider } from './SaleSlider'
export { default as HomeVideos } from './HomeVideos'
