export const REGISTRATION_POST_REQUEST = 'REGISTRATION_POST_REQUEST'
export const REGISTRATION_POST_SUCCESS = 'REGISTRATION_POST_SUCCESS'
export const REGISTRATION_POST_FAILURE = 'REGISTRATION_POST_FAILURE'

export const LOGIN_POST_REQUEST = 'LOGIN_POST_REQUEST'
export const LOGIN_POST_SUCCESS = 'LOGIN_POST_SUCCESS'
export const LOGIN_POST_FAILURE = 'LOGIN_POST_FAILURE'

export const LOGOUT = 'LOGOUT'
