export const GET_USER_DATA_REQEST = 'GET_USER_DATA_REQEST'
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS'
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE'
export const USER_DATA_RESET = 'USER_DATA_RESET'
